### ISSUE TITLE
Common header appears in storage modal, makes modal unresponsive.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/component-storage-selector#23]
Steps to reproduce:
1. Add a widget that uses storage selector to your presentation
2. Click the storage selector button
3. View storage modal

Result:
Notice that the storage modal is not responsive and only fills a small portion of the screen, the common header also appears - http://www.screencast.com/t/Y0TmwDEQ88r9

How it should work:
The modal should be fully responsive, there should be no common header in this modal - http://www.screencast.com/t/Iw4h8UNHWZi

OS:
OS X, Windows 7, Ubuntu 14.04

Chrome Ver:
41.0.2272.104

**Comment by btfrise** [comment]
@alanclayton FYI, this needs to be worked into your work schedule.

**Comment by stulees** [comment]
@btfrise @alanclayton FYI, this card in backlog - https://trello.com/c/lc5e8KcA/276-storage-selector-component . It is reliant on this card finishing - https://trello.com/c/HBDGppnc/326-in-app-storage-selection-improvements

**Comment by alanclayton** [comment]
@stulees Thanks

**Comment by alanclayton** [comment]
No longer an issue. Closing
